micronaut:
  application:
    name: productsService

datasources:
  default:
    url: jdbc:h2:mem:devDBTest;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ''
    driverClassName: org.h2.Driver
    dialect: H2
jpa:
  default:
    packages-to-scan:
      - 'com.angularlabs.domain.entity'
    properties:
      hibernate:
        hbm2ddl:
          auto: none

flyway:
  datasources:
    default:
      enabled: true